install:
	cp base_rules $(DEVKITA64)/
	cp base_tools $(DEVKITA64)/
	cp switch_rules $(DEVKITA64)/
	cp lib/switch.ld $(DEVKITA64)/aarch64-none-elf/lib/
	cp lib/switch.specs $(DEVKITA64)/aarch64-none-elf/lib/
